### ISSUE TITLE
jpl:prolog_in_java fails with 9.3.15

### ISSUE THREAD

**Issue by mcepl** [SWI-Prolog/packages-jpl#104]
When packaging this program from https://www.swi-prolog.org/download/devel/src/swipl-9.3.15.tar.gz tarball, this one test fails (previous version, 9.3.12, passed):

```
[  106s] test 84
[  106s]       Start 84: swipy:xsb_janus
[  106s] 
[  106s] 84: Test command: /home/abuild/rpmbuild/BUILD/swipl-9.3.15/build/src/swipl "-p" "foreign=:/home/abuild/rpmbuild/BUILD/swipl-9.3.15/build/packages/plunit" "-f" "none" "--no-packs" "--on-error=status" "-s"
 "/home/abuild/rpmbuild/BUILD/swipl-9.3.15/packages/swipy/test_xsb_janus.pl" "-g" "test_xsb_janus" "-t" "halt"
[  106s] 84: Working Directory: /home/abuild/rpmbuild/BUILD/swipl-9.3.15/build/packages/swipy
[  106s] 84: Test timeout computed to be: 10000000
[  106s] 8: % [7/23] trie:insert_nested_get ..................... passed (0.001 sec)
[  106s] 8: % [8/23] trie:insert_vars ........................... passed (0.000 sec)
[  106s] 8: % [9/23] trie:insert_variant ........................ passed (0.000 sec)
[  106s] 8: % [10/23] trie:insert_vars .......................... passed (0.000 sec)
[  106s] 77: % [4/12] archive:create_and_open_named_no_close ..... passed (0.020 sec)
[  106s] 69/86 Test SWI-Prolog/swipl-devel#81: jpl:prolog_in_java ...............***Failed    0.20 sec
[  106s] Error: Could not find or load main class .usr.share.java.junit4.jar:.usr.share.java.hamcrest.hamcrest.jar:src.main.java.jpl.jar:src.test.java.jpltest.jar
[  106s] Caused by: java.lang.ClassNotFoundException: /usr/share/java/junit4/jar:/usr/share/java/hamcrest/hamcrest/jar:src/main/java/jpl/jar:src/test/java/jpltest/jar
[  106s] 
```

[Complete build log](https://github.com/user-attachments/files/17871083/_log.txt) with all packages used and steps taken to reproduce.

**Comment by JanWielemaker** [comment]
The mentioned SWI-Prolog/packages-jpl@e3be3065f2c8e643bfee83fcb92545bb8afee03b seems to fix it (reproduced and tested on suse-tumbleweed Docker image)

**Comment by mcepl** [comment]
Hmm, it seems to me that `cmake/JUnit.cmake` is not included in the distribution tarball. Is it?

Even with adding this file as a patch it fails, see [build log](https://github.com/user-attachments/files/17873826/_log.txt).

**Comment by JanWielemaker** [comment]
> Hmm, it seems to me that `cmake/JUnit.cmake` is not included in the distribution tarball. Is it?

```
tar ztvf swipl-9.3.15.tar.gz | grep /jpl/cmake
drwxrwxr-x root/root         0 2024-11-14 13:38 swipl-9.3.15/packages/jpl/cmake/
-rw-rw-r-- root/root      2541 2024-11-14 13:38 swipl-9.3.15/packages/jpl/cmake/JUnit.cmake
```

It surely has this file as otherwise it should not configure the test at all (and fail during the cmake run on a missing file).    You are also still using the old one as it says `/usr/share/java/junit.jar:/usr/share/java/junit4.jar` at some point and it does not print the (new) message during configure where it found junit[4].jar

**Comment by mcepl** [comment]
On Sat Nov 23, 2024 at 1:29 PM CET, Jan Wielemaker wrote:
>> Hmm, it seems to me that `cmake/JUnit.cmake` is not included in the distribution tarball. Is it?
>
> ```
> tar ztvf swipl-9.3.15.tar.gz | grep /jpl/cmake
> drwxrwxr-x root/root         0 2024-11-14 13:38 swipl-9.3.15/packages/jpl/cmake/
> -rw-rw-r-- root/root      2541 2024-11-14 13:38 swipl-9.3.15/packages/jpl/cmake/JUnit.cmake
> ```

I see, I was patching in wrong directory (`cmake` in the root of the package)! Now fixed in https://src.opensuse.org/pool/swipl/pulls/6. Thank you!
