### ISSUE TITLE
Multi-threaded Queries, Terminating Queries and old Query.lock() not necessary anymore

### ISSUE THREAD

**Issue by ssardina** [SWI-Prolog/packages-jpl#15]
The JPL documentation includes a section on [Multi-Threaded Queries](https://jpl7.org/JavaApiOverview.jsp#Multi-Threaded%20Queries) that makes total sense. However, there seems to not be anymore the public static method `Query.lock` to be used in the applications.

All core query predicates (e.g., `hasSolution`) are synchronized static methods, but when combined with iteration, issues may arise if I understood well.

I went back even to the first commit of the repo and I couldn't find that `lock()` method, even though they are referred to in the source code, for example:

```
To ensure thread-safety, you should wrap sequential calls to
	 * this method in a synchronized block, using the static
	 * lock method to obtain the monitor.
	 * <pre>
	 * Query q = // obtain Query reference
	 * synchronized ( jpl.Query.lock() ){
	 *     while ( q.hasMoreElements() ){
	 *          Hashtable solution = q.nextSolution();
	 *          // process solution...
	 *     }
	 * }
```

**Comment by JanWielemaker** [comment]
Not 100% sure.  AFAIK, when JPL was initiated SWI-Prolog was single threaded and queries from multiple threads required a lock.  Since a long time SWI and JPL support threads.  The JPL creates
a number (configurable) of Prolog _engines_ and pools queries to Prolog to one of these engines.

**Comment by anionic** [comment]
The doc section "Multi-Threaded Queries" may still make sense, but it is obsolete; Jan implemented an engine pool for JPL long ago.  It looks like that document was updated for JPL7 down as far as "The Util class" but "Querying Prolog" onwards needs fixing - I'm on that - watch this space.

**Comment by ssardina** [comment]
Hi both, 

Thanks for your replies, highly appreciated! 

I have been looking at the code today and as Jan suggested and confirmed by anionic (are you Paul S?) there is now an implementation of SWI prolog engine pools, and for what I understood each Java thread is linked to a different SWI engine.

The `lock()` method is not there anymore, though I would imagine it could still be useful/necessary even within the same engine (in the same thread) right?

Also, let me see if I understood correctly: by default in the C-code there are max 10 SWI engines and each Java thread will be attached to a different one. So this would imply that if I have say 11 Java threads wanting to do JPL-Prolog, it won't work? I ask this because I may have way more than 10 agents (each a thread) trying to do Prolog....

@anionic: let me know if you need help, keep me posted on the doc. :-)

Thanks!

Sebastian

**Comment by JanWielemaker** [comment]
> The `lock()` method is not there anymore, though I would imagine it could still be useful/necessary even within the same engine (in the same thread) right?

No.  Two Java threads are never associated with the same Prolog engine as used to be the case when there was only one.   Locking here will effectively make the whole pool design useless.

I don't know the code when JPL is out of Prolog engines.  There are several things one can do, notably wait until one becomes available, create more or throw an error at the caller.  Once upon a time the number of Prolog engines was limited, but it is now only limited by the OS.

**Comment by ssardina** [comment]
Good point. So Query.lock() is totally not necessary, right, I get it.

I did a few testing and the pool of engines seems to re-use engines for threads that are finished. So there could never be more than 10 active threads using SWI, but once a thread finishes, it seems for what I have seen that the engine for that thread is re-used for another thread. I enabled some printout in JPL and the same engine seems to show up again in another thread...

Stil this may not solve my problem because I could have say 30 agents, all wanting Prolog at the same time, and they cannot just wait for another agent to die (may never die)..

So, Jan, are you saying that we can improve the JPL pool of engines to not have an upper bound (10 currently)? Or that there is no upper bound now already..  See this code in `jpl.c`

```
#define JPL_MAX_POOL_ENGINES 10    /* max pooled Prolog engines */
#define JPL_INITIAL_POOL_ENGINES 1 /* initially created ones */


```

**Comment by JanWielemaker** [comment]
I don't know the code very well.   I did little more than fix some compiler warnings and portability to it. I guess you can read the code yourself?

**Comment by ssardina** [comment]
Hi both,

Thanks for your input. 

I had a careful look at the code and run many experiments with many threads etc to see what was happening. The situation seems to be exactly as @anionic has described with a subtle point:

There is a pool of engines, at this point 10 (specified in the C code) and an engine is attached to a Query when this is activated by its thread. The engine is then freed when the Query closes (simple queries like `hasSolution` or `oneSolution` close the query right away). One in the pool it is available for any other query in any other thread (or the same thread), and so on. So, YES, the `JPL_MAX_POOL_ENGINES` dictates how many **concurrent opened** queries can be at any point, and not how many threads: the engines are shared across threads.

There is only one subtle point: _the first engine_. This is created at the start and seems that once used and attached in a thread, it can only be re-used by queries in that thread. So the first engine does not seem to be available to other threads after that, even if the query that used that engine was closed. 
@anionic , does this subtle point makes any sense to you?

I am curious that @JanWielemaker said one could have as many SWI engines as wanted, modulo OS limitations... This means we could potentially get rid of `JPL_MAX_POOL_ENGINES`...

**Comment by JanWielemaker** [comment]
The first one may be special because the first Prolog engine is still special and, unlike other engines, cannot be destroyed.  I think that also means you should make sure that the Java thread that created this engine stays alive.   There is no need for this Java/Prolog couple to do any work though and if they are just sitting there they should be fairly cheap.
I guess JPL_MAX_POOL_ENGINES should be a dynamic setting that can either be changed on the fly or specified as startup option.   Removing can be an option, but if you have a workload where the memory usage of Prolog queries is huge you may not run too many concurrently.

P.s. Note that engines cannot communicate `thread_local` predicates or global variables.  That means that you can only use these from Java in a single query.  If you fire two consecutive queries you may be talking to two different engines.

I'm not really into developing JPL, but happy to merge pull requests.

**Comment by ssardina** [comment]
Actually, I may keep it open until we complete at least steps 1-3 above.

Here is a first take on point 2:

https://github.com/ssardina-research/packages-jpl/wiki/Multi-Threaded-Queries

@anionic : what do you think to replace the text on the JPL doc? Also, note that the section "Terminating Queries" should also be updated/removed. For example, there is no `Query.rewind()` anymore, there is only `Query.close() `

**Comment by ssardina** [comment]
Actually, I may keep it open until we complete at least steps 1-3 above.

Here is a first take on point 2:

https://github.com/ssardina-research/packages-jpl/wiki/Multi-Threaded-Queries

@anionic : what do you think to replace the text on the JPL doc? Also, note that the section "Terminating Queries" should also be updated/removed. For example, there is no `Query.rewind()` anymore, there is only `Query.close() `

**Comment by anionic** [comment]
I've uploaded my rewrite of "Java API - overview" to org.jpl7, then found your "Multi-Threaded-Queries" page, which I like; undecided whether to add that as a separate page and keep the overview terse?

If you are willing to experiment, it would be interesting to know what actually happens if a thread tries interleaved solution retrieval, or passing an active query to another thread...

**Comment by ssardina** [comment]
Hi @anionic . I have much developed the explanation on Multithreaded, including termination, nested retrieval of solutions in a thread (error!), and even passing around query objects (active or non active) to various threads as you suggested.

Now that I understand it more clearly JPL is really quite powerful as is. If one uses the basic functionalities in a simple way (one-shot queries in the same thread), then one does not need to understand much. If one uses iterator type queries and multi-threading, then one has to be more careful and understand the few limitations. 

https://github.com/ssardina-research/packages-jpl/wiki/Multi-Threaded-Queries

I also explain the different type of queries one can use with JPL here:

https://github.com/ssardina-research/packages-jpl/wiki/Types-of-Queries:-One-shot-vs-Iterative

Cheers,

Sebastian
PS: as I am understanding the code, I am cleaning a few bits. For example, there are two very important methods in Query called `get1()` (linked to `hasMoreSolutions()` check) and `get2()` (linked to `nextSlution()`) that took me sometime to understand in detail partly because of their names. I think they should be called something like: `fetchNextSolution()` and `getCurrentSolutionBindings()`

**Comment by ssardina** [comment]
All three points above have been done (@anionic did the external doc already). I think this issue is now understood and addressed. There was no reference to `Query.lock()` in the actual source, only in the doc.

**Comment by JanWielemaker** [comment]
Looks correct to me.
