### ISSUE TITLE
Silence compilation

### ISSUE THREAD

**Issue by JanWielemaker** [SWI-Prolog/packages-jpl#17]
@anionic @ssardina,

I'm doing a lot of work moving the entire system to `cmake`, which should in the end make compilation on different platforms easy.  In the meanwhile I try to make the compilation entirely silent to make development a lot smoother.

JPL is a bit noisy in three places:

```
warning: [options] bootstrap class path not set in conjunction with -source 1.7
```

```
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

and on the Mac we get

```
[223/2089] Building C object packages/...eFiles/plugin_libjpl.dir/src/c/jpl.c.o
../packages/jpl/src/c/jpl.c:1791:11: warning: 'JNI_GetCreatedJavaVMs' is deprecated [-Wdeprecated-declarations]
  return (JNI_GetCreatedJavaVMs(NULL, 0, &n) ==
          ^
/System/Library/Frameworks/JavaVM.framework/Headers/jni.h:1940:1: note: 'JNI_GetCreatedJavaVMs' has been explicitly marked deprecated here
JNI_GetCreatedJavaVMs(JavaVM **, jsize, jsize *);
^
../packages/jpl/src/c/jpl.c:1875:11: warning: 'JNI_GetCreatedJavaVMs' is deprecated [-Wdeprecated-declarations]
  return (JNI_GetCreatedJavaVMs(&jvm, 1, &n) ==
          ^
/System/Library/Frameworks/JavaVM.framework/Headers/jni.h:1940:1: note: 'JNI_GetCreatedJavaVMs' has been explicitly marked deprecated here
JNI_GetCreatedJavaVMs(JavaVM **, jsize, jsize *);
^
../packages/jpl/src/c/jpl.c:1882:23: warning: 'JNI_CreateJavaVM' is deprecated [-Wdeprecated-declarations]
              : ((r = JNI_CreateJavaVM(&jvm, (void **)&env, &vm_args)) == 0
                      ^
/System/Library/Frameworks/JavaVM.framework/Headers/jni.h:1937:1: note: 'JNI_CreateJavaVM' has been explicitly marked deprecated here
JNI_CreateJavaVM(JavaVM **pvm, void **penv, void *args);
^
3 warnings generated.
```

Can we get rid of these (preferably by fixing rather than suppressing)?

**Comment by JanWielemaker** [comment]
Seems at least the latter is a consequence of my Mac using some ancient version of Java.  The first two are around on Ubuntu and Fedora as well though.

**Comment by ssardina** [comment]
OK,  I am having a look at it. I am getting my head around how to compile JPL. Seems I cannot compile it in isolation, I need the whole SWI distribution and even the core SWI first. Should one be able to compile JPL by itself alone? Is it so linked to the other bits of SWI? Maybe I am not understanding the whole package, it is indeed quite complex and I am not a ninja on this.. :-)

Doing a CMAKE configuration of the whole SWI is just great.

**Comment by anionic** [comment]
1) is it feasible to drop `-source 1.7` and conservatively modernise JPL sources to use a subset of Java API and syntax which compiles without warning under Java 7..12, yielding class files which run correctly under any JRE 7..12?

2) I am looking for the culprits...

3) isn't the `-Wdeprecated-declarations` option undesirable during production building? Can we use this only during development building? Looks like this JNI API was deprecated, then undeprecated, so suppressing is surely OK here?

**Comment by JanWielemaker** [comment]
> Doing a CMAKE configuration of the whole SWI is just great.

Cmake should work fairly nice, depending on your platform (which is?)  I think this might do:

```
git clone https://github.com/SWI-Prolog/swipl-devel.git
git submodule update --init packages/jpl
mkdir build
cd build
cmake -G Ninja -DINSTALL_DOCUMENTATION=OFF ..
ninja
```
Not tried ..,  You do need the core system because libjpl.so/dll/... links against libswipl.so/dll/...

You can of course drop `-G Ninja` and use `make` on Unix.   Haven't tested the cmake config on Windows.  I guess it should be close but there is some symlink handling and incidental Unix tool usage that is not yet made conditional.

**Comment by ssardina** [comment]
1. I am removing some of the warnings in JPL so that it can compile warning-free. What about `-target 1.7`? We should also aim to remove that ?

**Comment by ssardina** [comment]
Thanks for that. Amazing, yes it works;  `cmake` has done SWI and JPL only.

BTW, I use Linux Mint 19 (Ubuntu 18.04 - Bionic).

It compiled with target 1.7 (version 51).

I have clean-up a bit some JPL warnings, but they were mostly JPL using own deprecated API. I will continue tomorrow (down under in Australia day is almost over) and if I succeed will issue a pull request.

Good point @anionic . Would be good to modernize JPL source without breaking anything, but is there an advantage to drop the backwards compatibility? __Is there any price to pay whenbuilding old-fashioned class files?__

**Comment by JanWielemaker** [comment]
> Note that the JPL unit tests are still disabled for the cmake version. I'll have a look at that.

Pushed a patch for that.  You probably do not want to test the core.  To run the JPL tests, do

```
ctest -R jpl:
```

If you want to see the output, use

```
ctest -V -R jpl:
```

**Comment by anionic** [comment]
OK sorry I got the forwards compatibility wrong.

Here's how I got rid of the bootclasspath warning: I stole an OpenJDK 1.7 rt.jar from [](http://jdk.java.net/java-se-ri/7) and compiled with `-source 1.7 -target 1.7 -bootclasspath path/to/rt.jar`

Presumably it's legit to distribute this rt.jar buried somewhere in the sources?

**Comment by ssardina** [comment]
I have produced a branch in my repo that addresses a few issues that yield warnings at compile time (e.g., use of deprecated API, missing JavaDoc info; casting of Double without using deprecated constructor". This gets rid of Jan's report of these warnings:

```
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

That is, in my updated source I do not get that warning anymore. Good.

Now, before pushing a pull request though I want to understand `-source` and `-target` and what we want. I have Java SE 8 in my system. I cannot keep `-target 1.7` without also using `-source 1.7`:

```
[ssardina@Thinkpad-X1 java]$ javac -version
javac 1.8.0_181
[ssardina@Thinkpad-X1 java]$ javac  -target 1.7  org/jpl7/Atom.java
javac: target release 1.7 conflicts with default source release 1.8
``` 

My understanding is that Jan wants to aim to keep just `-target 1.7`, but modernized the sources to be 1.7+.  Well, seems you cannot specify `-target 1.7` without making sure the sources are also 1.7 max, either by compiling it with Java SE 7 or you add `-source 1.7`.

So, overall I think we need to keep both  `-target 1.7` and `-source 1.7` if we do want to make sure we produce 1.7 class files.

Said so, I quite do not understand why we need this at all. If someone gets JPL and has Java SE 1.7, it will compile and produce 1.7 versions; and if she/he has 1.8 it will produce 1.8 versions with no problem. Even 1.9 I guess but I haven't tested as I do not have that SE.

Since we are not distributing the JAR files themselves, why do we want to force 1.7?

**Comment by ssardina** [comment]
If we want to produce old platform class files/jars then we need to set the `-source` (e.g., `-source 1.7`) and also _set the bootclasspath to compile against the rt.jar (or equivalent) for the older platform._

If the second step is not taken, `javac` will warn with

`warning: [options] bootstrap class path not set in conjunction with -source 1.7
`
if we have a Java SE version in the system that is > 1.7, which is my case (I have Sun 1.8).

Check [this post](https://blogs.oracle.com/darcy/new-javac-warning-for-setting-an-older-source-without-bootclasspath)

The bootstrap class path refers to the `rt.jar` used, which is the runtime JAR and contains all the classes from Core Java AP (Strings, etc). In my machine, I am setting source to 1.7 but using  `rt.jar` of 1.8.

What could happen is that I use in JPL features of 1.8 in `rt.jar` that will be missing in a 1.7 system. We know this is not the case, but stil....

So, there seems to be THREE solutions Jan for this:

1. As @anionic suggested, we ship `rt.jar` of version 1.7. I feel a bit uneasy with this approach.
2. We add option `-Xlint:-options` to javac, because we know that we are not using features of `rt.jar` that are beyond 1.7.
3. We drop `-source 1.7` and `-target 1.7` all together and let the user compile JPL in whatever system she/he has. if they have Java SE 7, they will produce 1.7 jar; if they have Java SE 8 they will produce 1.8 version. All without any warnings because it will all be consistent.

BTW, I checked and the code is compatible with 1.5+, though 1.5 is now deprecated. It uses generics, so we cannot use 1.4.

Sorry for so much info, but I spent sometime investigating these issues and wanted to write this all down or otherwise I will totally forget once I switch into my teaching/research duties tomorrow... :-)

@JanWielemaker , I wait for order. I do have a branch with lots of warnings gone....

**Comment by JanWielemaker** [comment]
First of all, thanks for making the system compile clean again!  Then, about 1.7.  The reason why we distribute old versions is that we do not bundle Java with the __binary__ distributions.  We assume, which is fine on most platforms that the user install their Java and set the library search path such that `libjpl.so/dll` points at their Java installation.  So, I do think we want to bind to the oldest Java installation that is good enough for us and is still commonly used in production environments.

Now the `rt.jar`.  I agree we should avoid including that in our source distribution.  We know we are fine with any rt.jar >= 1.7.  I now understand the warning, so we can simply set an option to ignore it.

We could add an option to the CMAKE files that allows users to select their current Java version.  Might even be a good default as it typically only needs to be set differently for those building binaries that must run _everywhere_.  I will deal with that in due time.

P.s. I reverted the `toString` for now (not yet pushed; trying to get the Prolog-embedded-in-Java tests
to work).  If anyone wants a better implementation, fine with me and I'm happy to point at some alternatives.  I already pointed Wouter at those.

**Comment by ssardina** [comment]
ahh OK, I think I get it now. Yes, of course, you do have **binary** versions of SWI, which will come with the `jpl.jar` file already compiled, and you want that to be 1.7 just in case someone is running JRE 1.7. Of course! But then we need to keep both `-source 1.7` and `-target 1.7`

Agree, I would rather set the flag `-Xlint:-options` than include `rt.jar` 

Finally, what is this:

> P.s. I reverted the toString for now (not yet pushed; trying to get the Prolog-embedded-in-Java tests
> to work). If anyone wants a better implementation, fine with me and I'm happy to point at some 
> alternatives. I already pointed Wouter at those.

I am lost here... what are you referring to? is it related to backwards compat?

**Comment by JanWielemaker** [comment]
> I am lost here... what are you referring to? is it related to backwards compat?

Wasn't it you complaining that exceptions initiated an infinite recursion of exceptions?  Anyway, see the stuff I just pushed.    These changes also make `ctest -R jpl:` run both JPL test scripts (Java embedded in Prolog
and Prolog embedded in Java).

Let me know if you think the pull request (16) is ready to merge.  I'll on the above, adding a cmake option to compile the jar for compatibility, adding `-source 1.7 -target 1.7 -Xlint:-options` or leaving all three out (default).

**Comment by ssardina** [comment]
BTW, before I a go offline I updated the pull request #16 as they are related: better alignment with current Java spec. I detailed what that pull request involves there.

Note that  pull request includes the alignment of  `Query` to match the contract of Java standard iterator interface:  `hasNext()` does not move the pointer, but next() does it (similar for `hasMoreSolutins()` and `nextSolution()`). 

However, if you do not want to implement that change in the core JPL distribution, no problem, let me know and I can create a single pull request with just the warning issues fixed. I just wanted to have that implementation of the Iterator interface  (my students were very confused initially!) :-)

**Comment by JanWielemaker** [comment]
I'm happy with it as I have little opinion here except the more _standard_ is generally better.  I'll propose I'll merge the compatibility patches and wait for @anionic to see whether he has serious objections about the iterator.

I can deal with the git stuff ...

**Comment by ssardina** [comment]
> Wasn't it you complaining that exceptions initiated an infinite recursion of exceptions? Anyway, see the stuff I just pushed. These changes also make `ctest -R jpl:` run both JPL test scripts (Java embedded in Prolog
> and Prolog embedded in Java).

ohh yes, yes, you are referring to issue #13. Good. YES, that is the most serious issue by far. I did a solution without calling Prolog at all (faster). I will check yours tomorrow and let you know what I think, thanks for handling that, I was worry about that issue being forgotten.. ;-)

**Comment by ssardina** [comment]
> I can deal with the git stuff ...

I am curious. How do you do that? How do you take a part of a pull request? Cherry-pick?

**Comment by JanWielemaker** [comment]
> I am curious. How do you do that? How do you take a part of a pull request? Cherry-pick?

Yip start a branch, pull the request to the branch, rebase it and then use a combination of cherry-picking,`rebase -i` or squashed merge.   I've become pretty experienced with that :)  I'll make sure
the author isn't changed.

Seems I can merge the whole thing now, so I'll just do a quick review, merge, test and push.

**Comment by anionic** [comment]
Further thought: I fully support Jan's reversion of toString; Wouter can do his own thing outside of JPL (which was always intended as a minimal/necessary/sufficient *basis* for hybrid Java<->Prolog programming) and we ;-) won't have to maintain it...

Maybe JPL *development* should compile against a 1.7 rt.jar lest we stray outside the 1.7 API?

**Comment by ssardina** [comment]
> Yip start a branch, pull the request to the branch, rebase it and then use a combination of cherry-picking,`rebase -i` or squashed merge. I've become pretty experienced with that :) I'll make sure
> the author isn't changed.

geee, and then you do a triple jump & twist in the air? That is ninja git... `rebase`, I need to master that, seems powerful (and scary...)

Sure do as you think is best.

**Comment by JanWielemaker** [comment]
Hmm.  The patches break the tests.  See attachment
[jpl-test-output.txt](https://github.com/SWI-Prolog/packages-jpl/files/2460081/jpl-test-output.txt)

**Comment by JanWielemaker** [comment]
> Maybe JPL _development_ should compile against a 1.7 rt.jar lest we stray outside the 1.7 API?

I'm not a fan.  I don't like binary files in the source git and don't like possible license issues that may follow from including such material.   You as developer can of course call it that way.   I also like to keep warning levels as high as we can, also for end user builds.  It  warns people there may be something fishy.  I do like to make sure that on the main development platforms the compilation is silent, so I know immediately that any warning is a potential new issue.

**Comment by anionic** [comment]
At a glance, it's the tests wot need fixing; block them for now?

**Comment by JanWielemaker** [comment]
If we all agree, I'm happy with that.  How do I do that (keep in mind that I'm Java ignorant although I changed a few lines to get the tests running in the new cmake environment)?

**Comment by JanWielemaker** [comment]
I simply pulled the entire pull request to a local branch, built it and ran `ctest -V -R jpl:`.   I thought that was a good start.  The list is here.  The hashes have changed due to the rebase.

```
commit c7e35cbe8fd20a2a22958ec33830f1b44df6d813 (HEAD -> tmp)
Author: Sebastian Sardina <ssardina@gmail.com>
Date:   Tue Oct 9 16:57:42 2018 +1100

    Clean up uses of deprecated methods that gave warnings; Fix casting of Double for Java SE 9 - no use of deprecated consturctor; fixed JavaDoc warnings

commit 5c6d0f86e7ea40c1fb57c39640c0255729631a83
Author: Sebastian Sardina <ssardina@gmail.com>
Date:   Tue Oct 9 11:24:40 2018 +1100

    Resolve several internal calls to JPL deprecated methods

commit f21122c59f9479de52035c190e37813407d16d19
Author: Sebastian Sardina <ssardina@gmail.com>
Date:   Sat Oct 6 12:25:19 2018 +1000

    Added some standalone testing files - to test independent issues

commit 574724f4752d8ac0149e3cc34639041999153ed7
Author: Sebastian Sardina <ssardina@gmail.com>
Date:   Sat Oct 6 12:22:56 2018 +1000

    Added NoSuchElementException exception for iterator interface spec

commit 32a9fe66183a60dea873021598948c154f16713b
Author: Sebastian Sardina <ssardina@gmail.com>
Date:   Sat Oct 6 12:20:59 2018 +1000

    Fix w JavaDoc @param references

commit 6c24a2aaf069fc64d083f7d20833cff80fe9e022
Author: Sebastian Sardina <ssardina@gmail.com>
Date:   Sat Oct 6 12:10:15 2018 +1000

    Aligned Iterator API hasNext() and next() to standard Java contract, improved javadoc few places

commit ab1d05da130511571fc45e1c27be0be72d1383ec
Author: Sebastian Sardina <ssardina@gmail.com>
Date:   Fri Oct 5 11:43:52 2018 +1000

    Renamed get1() and get2() methods - Fixes #2

commit 9a51ce5b321646c69cf51c22f8243af415bae94f
Author: Sebastian Sardina <ssardina@gmail.com>
Date:   Sat Oct 6 10:40:00 2018 +1000

    Ignore IntelliJ and Maven aux outputs
    
    (cherry picked from commit 4b117325db48e1aa0ae50134ce8a6731cb5e98e2)

```

**Comment by anionic** [comment]
Unless you're using a very old JUnit, put `@Ignore` on a line above the `public void testXxxx()`

**Comment by ssardina** [comment]
See for example the first test error:

```
1) testRef6(org.jpl7.test.TestJUnit)org.jpl7.JPLException: this Term is not a JRef
51: 	at org.jpl7.Term.object(Term.java:559)
51: 	at org.jpl7.test.TestJUnit.testRef6(TestJUnit.java:910)
51: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
51: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
51: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

this is this test:


```
public void testRef6() {
		Term nullJRef = new Compound("@", new Term[] { new Atom("null") });
		Object nullObject = nullJRef.object();
		assertNull("@(null) .jrefToObject() yields null", nullObject);
	}
```


Here, I must have replace deprecated `nullJRef.jrefToObject()` with  I did to use `nullJRef.object()`. 
(BTW, the assertion message should have be changed as well to refer to `.object()`)

I assumed though that the new API `.object()` will do the job well but seems it is not? 

Indeed, I confirm that was [one of the changes](https://github.com/SWI-Prolog/packages-jpl/pull/16/commits/7a98b9b315107fac0eddeca1d1e55e63f2a46411#diff-11e49704964f11423dca4a62fd567088R916) to avoid warnings due to use of deprecated methods:

So, unless I am missing something big, that test should pass, so ignoring it would not be good :-) I can check it tomorrow if you want.

**Comment by JanWielemaker** [comment]
> So, unless I am missing something big, that test should pass, so ignoring it would not be good :-) I can check it tomorrow if you want.

Please do.  If you have junit.jar installed (default in /usr/share), running the ctest should work for you as well.
Have a good night!

**Comment by ssardina** [comment]
> Please do. If you have junit.jar installed (default in /usr/share), running the ctest should work for you as well.
> Have a good night!

OK yes will give it a go tomorrow, too late now and not thinking straight. Thanks for all. Cheers.

**Comment by JanWielemaker** [comment]
> Basically when you said you "pulled the entire pull request to a local branch", local branch of which repo? Of the JPL repo package-jpl alone? Or as part of the overall SWI system (within the `package/` subdir)?

Git submodules are complete stand alone git repos.   They are (by default) just not associated with a branch, so in `packages/jpl`

```
git checkout master
git pull                            # now nicely in sync and on a branch
git checkout -b tmp       # start a new branch
git pull <your stuff>       # get the stuff from you
<confirm the merge>
git rebase master         # rebase on top of master to make te relation easier to follow
```

Now build it:

```
cd ../../build
cmake ..
ninja                             # or make, but I prefer ninja
```

If you do not trust it did all dependencies right, you can do

```
ninja -t clean jpl
ninja
```

Or, using make

```
make -C packages/jpl clean
make
```

**Comment by ssardina** [comment]
Thanks a lot Jan for the patience. :-) I am learning git quite a bit on this thread..

I have managed to have a full swipl-devel repo with the jpl submodule and the pull from my repo on it. All good. I have done the merging, and everything looks as I want to test.

Then did `cd ../../build` which leaves me in `swipl-devel/build` as expected, run `cmake ..` and `make`, all compiles well, no warnings either as I am doing all with Java SE 8 and you removed the `-source -target`.

However, when I ran the test I get:

```
[ssardina@Thinkpad-X1 build]$ pwd
/home/ssardina/git/soft/prolog/swipl-devel.git/build
[ssardina@Thinkpad-X1 build]$ ctest -V -R jpl:prolog_in_java
UpdateCTestConfiguration  from :/home/ssardina/git/soft/prolog/swipl-devel.git/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/ssardina/git/soft/prolog/swipl-devel.git/build/DartConfiguration.tcl
Test project /home/ssardina/git/soft/prolog/swipl-devel.git/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 13
    Start 13: jpl:prolog_in_java

13: Test command: /usr/bin/env "SWI_HOME_DIR=../../home" "TEST_JPL=../../../packages/jpl/test_jpl.pl" "/usr/lib/jvm/java-8-oracle/bin/java" "-Djava.library.path=." "-classpath" "/usr/share/java/junit.jar:src/java/jpl.jar:src/java/jpltest.jar" "junit.textui.TestRunner" "org.jpl7.test.TestJUnit"
13: Test timeout computed to be: 9.99988e+06
13: [FATAL ERROR: at Wed Oct 10 18:40:25 2018
13: 	Could not open resource database "../../src/swipl.prc": No such file or directory]
1/1 Test #13: jpl:prolog_in_java ...............***Failed    0.09 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.09 sec

The following tests FAILED:
	 13 - jpl:prolog_in_java (Failed)
Errors while running CTest

```

Interesting, `../../src/swipl.prc` (from `build/packages/jpl`) is there!

```
[ssardina@Thinkpad-X1 build]$ l src/swipl.prc 
-rw-rw-r-- 1 ssardina ssardina 79K Oct 10 18:13 src/swipl.prc
```

your log txt file seems identical to mine, except you use `linux` instead of `build`.

I will keep trying or see if I can run the test manually...

**Comment by JanWielemaker** [comment]
I'll have a look.  Just hang on.

**Comment by JanWielemaker** [comment]
Hmmm.  Just cleaned the entire build tree completely and retried.  Works fine.  The test command indeed runs in `build/packages/jpl`.  Debugging that remotely is a bit hard :(  My first step would be to go this this directory and run the command with `strace -o x` in there. `strace` dumps the system calls, so you can see -notably- what files the system tries to open with what result.

```
/usr/bin/env "SWI_HOME_DIR=../../home" "TEST_JPL=../../../packages/jpl/test_jpl.pl" strace -o x "/usr/lib/jvm/java-8-oracle/bin/java" "-Djava.library.path=." "-classpath" "/usr/share/java/junit.jar:src/java/jpl.jar:src/java/jpltest.jar" "junit.textui.TestRunner" "org.jpl7.test.TestJUnit"
```

Now look in `x` searching for `swipl.prc`.   Note that I use Ubuntu 18.04, so our build environment is rather similar.  My Java is `/usr/lib/jvm/java-8-openjdk-amd64`.  Guess this shouldn't matter too much unless for some strange reason something is changing working directory.  

You can add `SWIPL_BOOT_FILE` to the environment, pointing at `swipl.prc` using an absolute path to avoid directory issues.

**Comment by ssardina** [comment]
Just to get heads up. I am trying the test code "manually" because I just cannot make the testing framework run via `cmake`. 

But I realize that, as excepted, some tests are not aligned with the new iterator interface implementation:

For example:

```
    public void testGetSolution1() {
        Query q = new Query("fail");
        q.open();
        q.nextSolution();
        assertTrue("an opened query on which getSolution has failed once is closed", !q.isOpen());
    }
```

will fail with an `NoSuchElementException`exception  which is correct, because q.nextSolution() is (wrongly) trying to advance to the next solution without being one! 

Here, we need to change the test to either check that the exception is thrown or replace nextSolution() with hasMoreSolutions().

In any case, lots of tests the failed are about `NoSuchElementException` so I expect that we just need to update the test cases to match the new Java-standard API for the iterator interface of Query class.

**Comment by ssardina** [comment]
> What thus "manually" mean here, i.e., what is the magic difference we can use to make the automatic test work?
> 

True, I was far from clear. Manual means really manual. I took the single test and run it in a ad-hoc new class by myself, not even using JUNIT. Horrible, I know... :-) The test set-up for JPL is complex, it will take me time to figure it out...

> Otherwise @anionic is probably right and we should either block, delete or fix the tests. Of course, this assumes that most JPL users use the iterator API correctly ... We'll see. If this happens not to be the case we'll get complaints and can decide what to do ...

mmm Let me make sure first I have not broken anything. Many issues seem to be with the iterator new API, that should be very easy to fix. I also want to check this `.object()` method.. :-)

YEs, would be nice to know what is the magic to make the Testsuite work!

**Comment by JanWielemaker** [comment]
> `strace`does not show anything

You mean just nothing relevant?  Could `java` be a shell script so we are tracing the shell rather than the executable?   If you examine the output, look for any ".prc" file it is trying.

"swipl.prc" is a zip file.  E.g.:

```
hppc823 (linux; master) 5_> unzip -t src/swipl.prc 
Archive:  src/swipl.prc
    testing: $prolog/state.qlf        OK
No errors detected in compressed data of src/swipl.prc.
```

Also `src/swipl -x `src/swipl.prc` should work fine.

**Comment by pmoura** [comment]
Regarding the main topic, on macOS using Java 10 and a just updated git version, I get the following build warnings:

```
[1058/2297] Building Java objects for jpl_jar.jar
org/jpl7/Term.java:508: warning: [dep-ann] deprecated item is not annotated with @Deprecated
	public Object jrefToObject() { // overridden in Compound and JRef
	              ^
org/jpl7/Term.java:519: warning: [dep-ann] deprecated item is not annotated with @Deprecated
	public final int listLength() {
	                 ^
org/jpl7/Term.java:568: warning: [dep-ann] deprecated item is not annotated with @Deprecated
	public static final Term objectToJRef(Object object) {
	                         ^
org/jpl7/Term.java:711: warning: [dep-ann] deprecated item is not annotated with @Deprecated
	public Object ref() { // overridden in JRef
	              ^
org/jpl7/JRef.java:88: warning: [dep-ann] deprecated item is not annotated with @Deprecated
	public Object jrefToObject() {
	              ^
org/jpl7/JRef.java:115: warning: [dep-ann] deprecated item is not annotated with @Deprecated
	public Object ref() {
	              ^
org/jpl7/JPL.java:360: warning: [dep-ann] deprecated item is not annotated with @Deprecated
	public static void halt() {
	                   ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
7 warnings
```

**Comment by ssardina** [comment]
> So MacOS' Java 10 wants deprecation denoted the modern way :-/ The cited methods have been deprecated for years, and could be removed now; also block any tests which use them. Alternatively, add the annotation.

I agree if @anionic  is happy with that. It is a good time to do some clean-up.

**Comment by ssardina** [comment]
@JanWielemaker , I am about to succeed and run the tests. The issue seems to be with the `src/swipl.prc` itself. Even if I do the initialization in CLI I get:

```

[ssardina@Thinkpad-X1 build]$ swipl -x src/swipl.prc 
[FATAL ERROR: at Wed Oct 10 22:24:50 2018
	Could not open resource database "src/swipl.prc": Inappropriate ioctl for device]
```

Of course I have no idea what this means, but I can do `swipl -x` with the `swipl.prc` in the system instal:

```
[ssardina@Thinkpad-X1 build]$ swipl -x /usr/local/src/swipl-7.6.4/unpacked-srcs/src/swipl.prc
Welcome to SWI-Prolog (threaded, 64 bits, version 7.6.4)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit http://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

```

**Comment by JanWielemaker** [comment]
Close!  Compiles clean.  The tests give 1 error and 1 failure:

```
51: There was 1 error:
51: 1) testRef6(org.jpl7.test.TestJUnit)org.jpl7.JPLException: this Term is not a JRef
51: 	at org.jpl7.Term.object(Term.java:559)
51: 	at org.jpl7.test.TestJUnit.testRef6(TestJUnit.java:912)
51: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
51: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
51: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
51: There was 1 failure:
51: 1) testRef7(org.jpl7.test.TestJUnit)junit.framework.AssertionFailedError: @(foobar) .jrefToObject() threw wrong JPLException: org.jpl7.JPLException: this Term is not a JRef
51: 	at org.jpl7.test.TestJUnit.testRef7(TestJUnit.java:928)
51: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
51: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
51: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
51: 
51: FAILURES!!!
51: Tests run: 120,  Failures: 1,  Errors: 1
```

**Comment by ssardina** [comment]
Great!

Yes, those are not related to the iterator anymore but to the `Term.object()` method. WIll investigate those today.

**Comment by ssardina** [comment]
All done Jan! All tests work well in my unit testing set-up. (using JUnit but independently of the suite)

This required updating the tests but also improving the way JREF are handled, especially the NULL case. I added issue #20  on that.

**Comment by ssardina** [comment]
@JanWielemaker , check this out:

```
[ssardina@Thinkpad-X1 build]$ ctest -V -R jpl:prolog_in_java
UpdateCTestConfiguration  from :/home/ssardina/git/soft/prolog/swipl-devel.git/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/ssardina/git/soft/prolog/swipl-devel.git/build/DartConfiguration.tcl
Test project /home/ssardina/git/soft/prolog/swipl-devel.git/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 13
    Start 13: jpl:prolog_in_java

13: Test command: /usr/bin/env "SWI_HOME_DIR=../../home" "TEST_JPL=../../../packages/jpl/test_jpl.pl" "/usr/lib/jvm/java-8-oracle/bin/java" "-Djava.library.path=." "-classpath" "/usr/share/java/junit.jar:src/java/jpl.jar:src/java/jpltest.jar" "junit.textui.TestRunner" "org.jpl7.test.TestJUnit"
13: Test timeout computed to be: 9.99988e+06
13: .........................................
13: .........................................
13: ......................................
13: Time: 0.044
13: 
13: OK (120 tests)
13: 
1/1 Test #13: jpl:prolog_in_java ...............   Passed    0.21 sec

The following tests passed:
	jpl:prolog_in_java

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.21 sec

```

I have no idea why it is not complaining anymore about `src/swipl.prc`, I suspect it was your last patch and I must have not done a fresh compile before.

Now one thing I needed was to also compile the `plunit` module. So here were the steps:

```
git clone git@github.com:SWI-Prolog/swipl-devel.git
cd swipl-devel/
git submodule update --init packages/jpl
git submodule update --init packages/plunit
mkdir build
cd build
cmake -DINSTALL_DOCUMENTATION=OFF ..
make
ctest -V -R jpl:prolog_in_java

```

The issue I had was that I had `LD_PRELOAD=/usr/lib/libswipl.so` !!

All done. Thanks for your patience and guidance. I learnt a few things beyond JPL!

**Comment by JanWielemaker** [comment]
Merged and pushed.  I kept all the individual commits as I think they are useful for the record.  Tagged some as
`TEST:`, etc.  Any commit that starts with `[A-Z]+:` is automatically added to the changelog that is produced with a new release.

We're not completely there.  In the Mac I get the following (running Oracle Java 10).   Am I right these are forgotten `@Deprecated`?  If so, I guess I can add them :)

I'll close the pull request.  If you did not make a branch, re-sync like below.  If you did make a branch, simply checkout master and pull.  Delete the old branch and start a new one for further pull requests.

```
cd packages/jpl
git checkout master
git fetch
git reset --hard origin/master
```

```
[814/2298] Building Java objects for jpl_jar.jar
org/jpl7/Term.java:508: warning: [dep-ann] deprecated item is not annotated with @Deprecated
	public Object jrefToObject() { // overridden in Compound and JRef
	              ^
org/jpl7/Term.java:519: warning: [dep-ann] deprecated item is not annotated with @Deprecated
	public final int listLength() {
	                 ^
org/jpl7/Term.java:570: warning: [dep-ann] deprecated item is not annotated with @Deprecated
	public static final Term objectToJRef(Object object) {
	                         ^
org/jpl7/Term.java:714: warning: [dep-ann] deprecated item is not annotated with @Deprecated
	public Object ref() { // overridden in JRef
	              ^
org/jpl7/JPL.java:360: warning: [dep-ann] deprecated item is not annotated with @Deprecated
	public static void halt() {
	                   ^
Note: org/jpl7/fli/atom_t.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
5 warnings
```

**Comment by ssardina** [comment]
Thanks Jan, great job yours. 

Strange those warnings, why I am not getting them. Can't be the Java version (I use Oracle Java SE 8).

I will annotate them doing your process and push another pull request, don't worry.

**Comment by ssardina** [comment]
Those errors are gone in Java SE 10. Should we close this @JanWielemaker ?
