### ISSUE TITLE
JPL regression, possibly caused by cmake related changes

### ISSUE THREAD

**Issue by pmoura** [SWI-Prolog/packages-jpl#19]
```
$ swipl
Welcome to SWI-Prolog (threaded, 64 bits, version 7.7.19-181-g0bab0134e-DIRTY)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit http://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- use_module(library(jpl)).
true.

?- jpl_terms_to_array([x, [1, a, 7, [y,z]], k, [], 3.14, foo(bar)], Array).
ERROR: Java exception: java.lang.UnsatisfiedLinkError: no jpl in java.library.path: [/Users/pmoura/lib/swipl/lib/x86_64-darwin, /Users/pmoura/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
^  Exception: (12) catch(jpl:jpl_set_instance(array(class([org, jpl7], ['Term'])), array(class([org, jpl7], ['Term'])), <jref>(0x7f8463c44fe0), 0, {x}), error(type_error(acyclic, _2354), context(jpl_datum_to_type/2, _2360)), jpl:throw(error(type_error(acyclic, _2354), context(jpl_set/3, _2360)))) ? abort
% Execution Aborted
```

**Comment by JanWielemaker** [comment]
Something to keep in mind :(  as is, how it is linked is very much in flux.  Works for me if I add the directory with `libjpl.so` to `LD_LIBRARY_PATH` (I think `DYLD_LIBRARY_PATH` on MacOS).

**Comment by pmoura** [comment]
I'm unable to get it to work (tried both `LD_LIBRARY_PATH` and `DYLD_LIBRARY_PATH`). The odd thing is that, of the 11 Logtalk tests that require JPL, a single one fails. I have reduced the failed test to the queries above.

**Comment by JanWielemaker** [comment]
Link logic in MacOS is completely different from Linux ...  It is weird that this specific test fails though.  Let us first settle the rest.

**Comment by ssardina** [comment]
I agree would be good to close the other issues, and then move to the new ones like this one.

Just for your info, I have a Linux box and I needed to add the paths to `libjava.so` and `jvm.so` to `LD_LIBRARY_PATH`  but even to load the library.

I also needed to have this `LD_PRELOAD=libswipl.so` but that is not your issue, it is complaining in not finding `libjpl.so`.

**Comment by pmoura** [comment]
Just to confirm that with today's update to JPL, and with:

```
$ echo $LD_LIBRARY_PATH
/Users/pmoura/lib/swipl/lib/x86_64-darwin

$ echo $DYLD_LIBRARY_PATH
/Users/pmoura/lib/swipl/lib/x86_64-darwin

$ otool -L /Users/pmoura/lib/swipl/lib/x86_64-darwin/libjpl.so 
/Users/pmoura/lib/swipl/lib/x86_64-darwin/libjpl.so:
	/Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home/lib/server/libjvm.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libswipl.7.dylib (compatibility version 7.0.0, current version 7.7.19)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
```

I still get:

```
$ swipl
Welcome to SWI-Prolog (threaded, 64 bits, version 7.7.19-193-g2a9e328f2-DIRTY)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit http://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- use_module(library(jpl)).
true.

?- jpl_terms_to_array([x, [1, a, 7, [y,z]], k, [], 3.14, foo(bar)], Array).
ERROR: Java exception: java.lang.UnsatisfiedLinkError: no jpl in java.library.path: [/Users/pmoura/lib/swipl/lib/x86_64-darwin, /Users/pmoura/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
^  Exception: (12) catch(jpl:jpl_set_instance(array(class([org, jpl7], ['Term'])), array(class([org, jpl7], ['Term'])), <jref>(0x7fd70053bed0), 0, {x}), error(type_error(acyclic, _2348), context(jpl_datum_to_type/2, _2354)), jpl:throw(error(type_error(acyclic, _2348), context(jpl_set/3, _2354)))) ? 
```

**Comment by JanWielemaker** [comment]
I think it is fixed now.  The issue was caused by different ways in which cmake sets up search for dependent libraries that caused the JVM not to find `libjpl.so/dll/...`  There was an edit of `LD_LIBRARY_PATH` (Mac `DYLD_LIBRARY_PATH`) in `jpl.pl` claiming this would be used, but that is most likely only correct on Windows.  I now changed that to use the `-Djava.library.path=` JVM init option.  That fixed the issue on Linux.

On MacOS this appeared more complex because, although one is supposed to use `.bundle` or `.so` for native plugins, Oracle JVM doesn't seem to be looking for these.   So I changed the name back to `libjpl.dylib` and than added some magic to make Prolog look for __both__ `.so` and `.dylib` on MacOS ...

Apple should compensate developers for torturing them ...

Please test and close if it works.

**Comment by pmoura** [comment]
All the failures, both the regression I described above and the Logtalk Java unit test error, are now fixed. The only thing remaining to clean seems to be the `deprecated item is not annotated with @Deprecated` warnings at build time. Good work.

**Comment by ssardina** [comment]
Incredible job Jan... @pmoura I will look at those missing deprecated items, we want zero warnings.
