### ISSUE TITLE
Get functor name for COMPOUND

### ISSUE THREAD

**Issue by ssardina** [SWI-Prolog/packages-jpl#24]
Compound allows to check whether it has a given functor name and arity (`.hasFunctor`) and to extract each argument (`.arg(n)`).

However, there is nothing to extract the name of the functor.

Introduce `.getFunctor()` method.

**Comment by anionic** [comment]
?? Compound has
`public final String name()`

**Comment by ssardina** [comment]
Sorry, don't know what I was thinking of, the `name` property is just the functor name. There is also a `hasFunctor` to check for name + artity. All good. Thanks for replying anyways!
