### ISSUE TITLE
Setting CLASSPATH from within SWI-Prolog ignored by JPL

### ISSUE THREAD

**Issue by pmoura** [SWI-Prolog/packages-jpl#3]
If the `CLASSPATH` environment variable is set using the `setenv/2` predicate before loading the `jpl` library, its new value is ignored. The only workaround seems to be setting the environment variable before starting SWI-Prolog. Tested with SWI-Prolog 7.3.7 and the bundled version of JPL.

**Comment by anionic** [comment]
On 05/10/2015 14:06, Paulo Moura wrote:
> If the |CLASSPATH| environment variable is set using the |setenv/2|
> predicate before loading the |jpl| library, its new value is ignored.
> The only workaround seems to be setting the environment variable
> before starting SWI-Prolog. Tested with SWI-Prolog 7.3.7 and the
> bundled version of JPL.

?? This certainly wasn't true on Windows up to 7.3.0

Welcome to SWI-Prolog (Multi-threaded, 32 bits, Version 7.3.0)
Copyright (c) 1990-2015 University of Amsterdam, VU Amsterdam
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to redistribute it under certain conditions.
Please visit http://www.swi-prolog.org for details.

For help, use ?- help(Topic). or ?- apropos(Word).

1 ?- setenv('CLASSPATH', foo).
true.

2 ?- jpl_call('java.lang.System', getProperty, ['java.class.path'], Path).
Path = 'c:/swipl-7.3.0/lib/jpl.jar;foo'.

In library/jpl.pl Jan prepends the absolute pathname of jpl.jar to 
CLASSPATH

add_jpl_to_classpath :-
	absolute_file_name(jar('jpl.jar'),
			   [ access(read)
			   ], JplJAR), !,
	(   getenv('CLASSPATH', Old)
	->  true
	;   Old = '.'
	),
	(       current_prolog_flag(windows, true)
	->      Separator = ';'
	;       Separator = ':'
	),
	atomic_list_concat([JplJAR, Old], Separator, New),
	setenv('CLASSPATH', New).

Is it possible you have initialised JPL before calling setenv?

Which OS?

Paul Singleton

**Comment by pmoura** [comment]
Using Mac OS X 10.11 (El Capitan). I can no longer reproduce the problem with SWI-Prolog 7.3.8. But the bug was not found by me. I'm trying to get more details.

**Comment by JanWielemaker** [comment]
Seems odd to me.  As long as JPL is loaded after setting CLASSPATH from Prolog, it should be picked up unless Java gets the environment variable in some non-standard way.  Depending on the OS, Prolog's setenv/2 maps to the C library setenv() or putenv() API.  This surely used to work.

Setting PATH, LD_LIBRARY_PATH or whatever is needed to find the shared objects only works on Windows.  All *nix systems I know about ignore runtime changes to the variable that controls the shared object search path.

**Comment by pmoura** [comment]
Got the code from the programmer that found the issue. It was a mistake on the code that resulted in the library being loaded before setting the `CLASSPATH` variable. Sorry for the false alarm.
