### ISSUE TITLE
JPL not compatible with SWI-Prolog 8.1.23

### ISSUE THREAD

**Issue by giuseta** [SWI-Prolog/packages-jpl#36]
Hello everyone,

I am using:

- SWI-Prolog 8.1.23
- JPL 7.4.0 (jar deployed in Maven Central)

If I perform this simple query
```       
 Query q1 = new Query(
    "use_module",
    new Term[]{new Compound("library", new Term[]{new Atom("lists")})}
);
```
I obtain the following error:
`org.jpl7.JPLException: unsupported blob type passed from Prolog`
Whereas, with SWI-Prolog 8.1.21 the query is executed without errors. I tested that by using an 11-day-old docker image deployed here: [https://hub.docker.com/repository/docker/giuseta/cplint-trill](https://hub.docker.com/repository/docker/giuseta/cplint-trill)

I would be very grateful for any information on solving the issue. Of course, I am keen to provide more information.

**Comment by JanWielemaker** [comment]
I don't know what _JPL 7.4.0 (jar deployed in Maven Central)_ means.  You must use the jar that is shipped with SWI-Prolog, as well as the jpl.dll/so/... from SWI-Prolog.  8.1.22 breaks binary compatibility of the SWI-Prolog C interface.    Some of the constants also appear in the JPL classes.  I have updated these and all pases the bundled tests again.  Note that SWI-Prolog can not report terms of type `rational`, which are not (yet) supported by JPL.

**Comment by giuseta** [comment]
I mean the one deployed here: [https://search.maven.org/artifact/jpl/jpl](https://search.maven.org/artifact/jpl/jpl)
Until a few weeks ago, I was able to use this version, because It was convenient to simply add 
```
<dependency>
  <groupId>jpl</groupId>
  <artifactId>jpl</artifactId>
  <version>7.4.0</version>
</dependency>
```
in the pom file of my Java application. Are you saying that the JPL library deployed in Maven Central is not official?

**Comment by JanWielemaker** [comment]
> Are you saying that the JPL library deployed in Maven Central is not official?

I don't know how things get into Maven, but surely I have nothing to do with it.   Version 8.1.22 and later require a new version of JPL and each binary version of SWI-Prolog ships with a matching jpl.jar and jpl.so/dll/...    That is all I can say.   My advice would be to either track the maintainer of the Maven version and request an update or use these files from the Prolog release to your Java project.  I don't know how the latter works in Maven, but it is definitely the reliable route.

**Comment by javatlacati** [comment]
@giuseta as Jan stated, generally every swi-prolog come with its own compatible jpl. Someone uploaded the jars, did all the boring signature process in order to make them available but as you may see from the dependency definition:

* group-name is not standard, it should be something like com.github.swi-prolog
* artifact id is just jpl, I think it should be something like packages-jpl

So what you see is a very old maven dependency and that's why probably the person that uploaded that version is no longer maintaining it.

You cand find the versions at https://github.com/SWI-Prolog/packages-jpl/releases

and unfortunately, in order to get the library working with your maven project, you will need to import manually the library by either adding it into a folder and declare your dependency as "system" or by installing the jar at your local maven repository.

**Comment by JanWielemaker** [comment]
@javatlacati Thanks for this comment.   Note that the _releases_ are just snapshots of the source.  The useful stuff (the jar and shared object/dll) is not in there and you cannot build JPL separately, it is part of the full SWI-Prolog build.   Most binary distributions include it.

**Comment by giuseta** [comment]
I got it, thank you very much for your help.

> and unfortunately, in order to get the library working with your maven project, you will need to import manually the library by either adding it into a folder and declare your dependency as "system" or by installing the jar at your local maven repository.
That's what I did, I declared the dependecy with scope "system" and provided the path to the jar. Thank you again.

**Comment by ssardina** [comment]
Hi @giuseta @javatlacati 

Just want to follow up on this and let you know that the JPL repo now is a Maven-project, so one can get the latest JAR package (containing the Java API) directly via Maven:

https://jpl7.org/DeploymentJava

Of course one still needs to have an SWIPL system installed to get SWI-Prolog itself and the C-native code part of JPL.

**Comment by giuseta** [comment]
Hi

this is great, thank you very much for your work. We will surely add JPL as
Maven dependency in our project.

Best wishes
Giuseppe

Il sab 27 giu 2020, 00:10 Sebastian Sardina <notifications@github.com> ha
scritto:
