### ISSUE TITLE
Memory leak with JPL (atoms are never GC'd by SWI)

### ISSUE THREAD

**Issue by edwinchoi** [SWI-Prolog/packages-jpl#4]
There is an issue with JPL when embedding SWI-PL in a JVM- whenever you pass an atom from the JVM to SWI-PL, the library allocates and uses the memory in a way that the memory can't be freed. 
This can be easily reproduced by creating a Prolog predicate `testpred(_).`, and calling it with a random string through JPL. With a 1M string, it does not take very long for the resident set to increase to many GB.

I narrowed the issue down to the creation of a functor with the atom as its name when passing the atom to SWI. This results in the atom's reference count being incremented by 1, and for whatever reason, this prevents the atom from being GC'd for the lifetime of the engine.

Unregistering the atom on finalize addresses the issue, but that's a hack... the memory allocated for the functor_t would not be freed, and would hold a reference to an invalid location in memory.

**Comment by JanWielemaker** [comment]
I don't know that much about JPL.  Two remarks though:

  - functors are not subject to GC currently in SWI-Prolog
  - On the other hand, I have no idea why passing a string as an atom needs to create a functor.

I'll send a mail to the JPL maintainer.

**Comment by anionic** [comment]
I have no idea why a functor is created here, but AFAIK it has always been that way; it may originate in a misunderstanding of the FLI. I am rather less familiar with the design rationale for the Java-calls-Prolog side of JPL (than my Prolog-calls-Java side), and wary of breaking it. I've confirmed that atoms created this way are immune to atom garbage collection. Regarding Edwin's hack: if the atom is unregistered, I guess that most of the memory would be reclaimed? If the functor is never referred to again, would its invalid memory reference ever be an issue?

I shall try to find time to figure out whether the functor creation can be bypassed, but I can only easily test JPL changes under 64-bit Windows 10, and don't want to require Jan to revisit the considerable work he did getting JPL to its current multiplatform stability.

**Comment by JanWielemaker** [comment]
The unregister hack leaves a functor struct with a pointer into the dark woods.  If you are lucky, nothing really bad happens, but just trying to allocate the same thing again is not unlikely to crash the system.   Once it is an isolated fix I guess it shouldn't be too hard to merge that into the main source.

**Comment by JanWielemaker** [comment]
Class `Atom` was using a rather peculiar way for turning a term handle into an atom from a string.   This is now fixed using 7d885abd551764fcced2ff3418bc731428bc1e21 and 4d6638c190b48e8ef82ad94d9976478fd9630dd0
