### ISSUE TITLE
Integrate/refactor term methods in Util into Term

### ISSUE THREAD

**Issue by ssardina** [SWI-Prolog/packages-jpl#45]
The majority of methods in `org.jpl7.Util` are tools for `Term`

I suspect this was something that was left there without refactoring into `Term` and is now quite confusing, with some `Term` manipulation methods in class `Term` and some in `Util`. For example we have a `Util.isList(Term)` but we have a `Term.isNil()` to check for empty list. 

An more obvious example is the creation of a `Term` from a String, done now by `Util.textToTerm(String text)`. This surely is better in the `Term` class as a static method.

I suggest we refactor and move all manipulation of term into `Term`, most of them are there already, and provide when necessary static and instance methods.

It is confusing and error-prone for the user of JPL to think that some term tools are in `Term` and some in `Util`.

@JanWielemaker do you support this?

**Comment by JanWielemaker** [comment]
> do you support this?

I fully trust you where it comes to Java.   I guess you'll make sure the old stuff keeps working and is marked as deprecated?

**Comment by ssardina** [comment]
Yes, for sure! Will be Mark deprecated with a reference to the new method.

Good, thanks!

**Comment by ssardina** [comment]
Done in 8d10d78226c9758de773a663bdbd0ddc74d0f3c3 and cd9239a23302505effd83bde3c650fe2f96b3671
