### ISSUE TITLE
Remove Changelog file

### ISSUE THREAD

**Issue by ssardina** [SWI-Prolog/packages-jpl#64]
There is a very old [Changelog](../blob/master/ChangeLog) with the last change in 2008. 

Given that this project is now in git it is not necessary or convenient to keep track of that file manually.

**Comment by JanWielemaker** [comment]
Please just remove and push to `master`.  No need to review :)

**Comment by ssardina** [comment]
Correct. All those minor changes I am doing them on master, don't worry. I just put them here for me to remember to do them (as they come up while doing other stuff and don't want to add those commits to other unrelated changes). 

I do PR only for non-minor changes/updates.

Thanks.

**Comment by ssardina** [comment]
Done in f69f239aadc1d09acf5437a652f35a54f58adb40
