### ISSUE TITLE
Move file ISSUE to the doc pages

### ISSUE THREAD

**Issue by ssardina** [SWI-Prolog/packages-jpl#68]
There is an [ISSUES](../blob/master/ISSUES) file that needs to be moved to the doc pages

**Comment by ssardina** [comment]
The file explains things related to the C-based implementation (clearly there are some outdated stuff, like calling the lib `libpl.a` right?).

@JanWielemaker @anionic , how correct is all this text? I want to include whatever is necessary under the doc of JPL for potential developers/users:

> On Unix systems, SWI-Prolog is normally   compiled as an application and
> static library (lib/$PLARCH/libpl.a). First of all this is easier ported
> on  may  Unix  systems  and  second,   shared  object  require  position
> independent code (-fpic) and  this  is   (depending  on  the  processor)
> generally slower than application code running at a fixed address.
> 
> We link jpl.so using -lpl, so it is   linked  to the dynamic libpl.so if
> Prolog is configured using  -enable-shared  or   to  the  static libpl.a
> otherwise. On ELF  systems  that   can  handle  position-dependent (i.e.
> compiled _without_ -fpic) code in  shared   objects  this works fine. If
> libjpl.so is loaded directly from Java  it   will  use the Prolog kernel
> included in libjpl.so. If  it  is   invoked  through  Prolog, the Prolog
> application is before libjpl.so in the ELF search path and therefore all
> Prolog symbols are resolved against the application.
> 
> There are two drawbacks to this approach.  The libjpl.so file could have
> been a small and version independent library,  while it is now bulky due
> to the embedded Prolog engine and version dependent.
> 
> Summarising, if your OS cannot  load   position  dependent .so files you
> MUST configure SWI-Prolog using --enable-shared. If  it can (Linux), the
> choice is yours and depends on  the   performance  penalty  paid on your
> processor (approx. 7% on  an  AMD  Athon),   how  you  wish  to  arrange
> versioning and how keen you are on memory sharing.

**Comment by JanWielemaker** [comment]
I think this is all old stuff, very little or nothing of which is still relevant.   Surely, SWI-Prolog is now in all platforms in `lbswipl.so/dll/dylib/...` and there is little advantage in static linking except for i386 on ELF (POSIX) systems where static linking indeed gives faster executables due to the poor support for position independent code and the small number of CPU registers, one of which is needed to deal with PIC.   Anyway, few people still use i386.

**Comment by anionic** [comment]
Simplest is to just lose it. If building SWI Prolog for i386/ELF is still supported, and there's a FAQ (ha! not "F") for that, then archive these notes with that? I wouldn't want any modern JPL user to come across this and worry about it. Is there a natural home for now-misleading historical stuff?

**Comment by JanWielemaker** [comment]
> Is there a natural home for now-misleading historical stuff?

/dev/null :smile: The other one is the git history.  Nothing ever gets lost in git ...

**Comment by ssardina** [comment]
Excellent, I supposed all this but didn't know if there was some important niche that was using this stuff.

I totally agree with @anionic and that's precisely my aim to all the clean-up: do not confuse users and provide just the necessary and current info. 

Great, removed in a790fe4
