### ISSUE TITLE
jpl.dll missing

### ISSUE THREAD

**Issue by pcoenen** [SWI-Prolog/packages-jpl#7]
Hello,

I was trying to install the prolog JPL on Windows, the installation guide says that I have to copy past the jpl.jar and the jpl.dll.

Both these files are currently missing, I assume that this is an old installation guide ?

Are there new instructions for Windows ?

Thanks in forward !

**Comment by JanWielemaker** [comment]
All JPL files are in the default Windows binaries.  Don't move or copy anything.  That is the best recipe 
to make things fail.  Just make sure you have Oracle JDK installed and all should work just fine.
