### ISSUE TITLE
Remove obsolete JPL web page in SWIPL pages

### ISSUE THREAD

**Issue by ssardina** [SWI-Prolog/packages-jpl#71]
This page is obsolete: https://www.swi-prolog.org/packages/jpl/

Can we remove that and add a link to https://jpl7.org/ at least for now?

I guess that is part of main SWIPL so I have no access.

Everything there has been migrated and updated in the current doc except for [this](https://www.swi-prolog.org/packages/jpl/java_api/low-level_interface.html), which is a nice explanation of the JNI part. I have made a copy and eventually will incorporate it into the [Developing JPL](https://jpl7.org/DevelopmentJPL) section in the doc.

**Comment by JanWielemaker** [comment]
After a bit of search I found this in `packages/jpl` of the plweb-www.git repo.   As you need to create PRs for that anyway :smile:

**Comment by ssardina** [comment]
Done in PR: https://github.com/SWI-Prolog/plweb-www/pull/37

**Comment by ssardina** [comment]
Merged in https://github.com/SWI-Prolog/plweb-www/pull/37
