### ISSUE TITLE
Update Java FAQ in SWIPL doc

### ISSUE THREAD

**Issue by ssardina** [SWI-Prolog/packages-jpl#72]
Hi @JanWielemaker 

Sorry to bother you so much but I am trying to clean-up all the rough corners so we get an up-to-date set-up with as little as possible confusing elements floating around.

In doing so it would be nice to update, elaborate this page:

https://www.swi-prolog.org/FAQ/Java.html

- Add pointer to github repo for JPL
- Add pointer to documentation
- Update link to examples
- Give credit to Paul Singleton and Fred Dushin as their original creators.
- etc..

Is there any way I can update that page? I would like to beef-up JPL for those coming from Java.

May also want to do some updates here: https://www.swi-prolog.org/pldoc/doc_for?object=section(%27packages/jpl.html%27)

BTW, someone commented there recently (May 2020) that it works out of the box and provided nice examples, I will put them into the example pack, they are neat.

**Comment by JanWielemaker** [comment]
The FAQ is in the plweb-www.git repo.   Please update as you see fit.   I'm afraid it isn't maintained very well :cry:

**Comment by ssardina** [comment]
Excellent, easy. Did the other now because it was easy (change for a pointer to latest JPL doc).

Will do this one later, as it takes a bit more time.

Thanks.

**Comment by ssardina** [comment]
Excellent, it was easier than what I thought. I updated the FAQ to be decent and with no old info and all updated pointers. Done, put it in the same PR: https://github.com/SWI-Prolog/plweb-www/pull/37

**Comment by JanWielemaker** [comment]
Ok.  Done?  Then I'll merge ...   The only thing I don't want is to be named designer of JPL :)  I'll fix that.

**Comment by ssardina** [comment]
:-) ah, sorry about that. I thought you had designed a big part of the FLI native part.

But am I crazy or it was not merged, just closed? I mean PR https://github.com/SWI-Prolog/plweb-www/pull/37

**Comment by JanWielemaker** [comment]
It is merged.  Somehow github doesn't handle a PR that is edited before being pushed very well.   Just pull and you'll see your edited commits.

**Comment by ssardina** [comment]
Yeap, I checked the file and my updates are there despite the PR not saying "Merged" as you pointed out.

But relevant pages still render the old version (e.g., https://www.swi-prolog.org/FAQ/Java.html). 

Do they update with version releases?
