### ISSUE TITLE
Minor error in JPLtest.java

### ISSUE THREAD

**Issue by dtonhofer** [SWI-Prolog/packages-jpl#84]
So I was checking whether I can call Java-to-Prolog tests from Junit5 with Maven and...

A little error in JPLTest (`packages/jpl/src/test/java/org/jpl7/junit/JPLTest.java`)

```
    public static final boolean report =
            (System.getenv("REPORT") == null ? true
                    : System.getenv("REPORT") == "true");
```

The second `==` should be `equals()` or better `"true".equalsIgnoreCase(System.getenv("REPORT") )`

**Comment by JanWielemaker** [comment]
Thanks.   Changes as suggested in c81e67bb9fd2f0f0d6b3004339cf156317729448.
