### ISSUE TITLE
create or call java object from prolog

### ISSUE THREAD

**Issue by Zohreh-Mehrafrooz** [SWI-Prolog/packages-jpl#95]
I created a simple class in java named Test.java as follows:
package test;
public class Test {
	
	public static void main(String argv[]) {
	System.out.print("Hello World! \n");
	}
}
and I want to create one object of the above Class from prolog through:
?-  jpl_new('test.Test',[],JRef). 
Or 
?- jpl_new('Test',[],JRef)

For my classpath, I have:
?- jpl_call('java.lang.System', getProperty, ['java.class.path'], Path).
Path = 'c:/program files/swipl/lib/jpl.jar'.

I coppied Test.class in the above path, and I received the error:
ERROR: Java exception: java.lang.NoClassDefFoundError: test/Test
Or
ERROR: Java exception: java.lang.NoClassDefFoundError: Test

I ran the Factorial example from my java IDE and every thing is fine. But, when I want to run from SWI-prolog, I will go to the above error. I would appreciate it if anyone has any idea and can help me. 
Regards,

**Comment by anionic** [comment]
[this is for the record: I sent this 20/May/2022 as a private email reply]

You misunderstand the Java class search path: read

  [Setting the Class Path](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/classpath.html) in Oracle's Java documentation

I think we would all recommend that you do not copy your own files into swipl directories.

Instead, add a path entry (for Windows, separated by semicolons) to your IDE directory *containing* your root package (test).

In my case, I might call

  `setenv('CLASSPATH', 'C:/Program Files/swipl/lib/jpl.jar;C:/shared/workspace42/MyProject')`

before any JPL call is made, which enables JPL to find and load

  C:/shared/workspace42/MyProject/test/Test.class

You will need to figure out, and substitute, your own local path to the directory which contains your test/Test

Paul Singleton

**Comment by Zohreh-Mehrafrooz** [comment]
Dear Paul, Thanks a lot for your help. I want to inform you that my problem solved. I copied project packages include ".class files" from bin folder and pasted in the main folder of project, I mean in "C:\Users\zohre\eclipse-workspace\MyProject", and it worked. 

Thanks and regards, 
Zohreh
